version: '2'
services:
  app:
    user: root
    image: knockout-assignment:latest
    command: [app]
    volumes:
      - .:/srv/apps/knockout-assignment/app/
      - ./logs/knockout-assignment:/srv/apps/knockout-assignment/logs
    depends_on:
      - kafka
    links:
      - kafka

  ## Confluent Stack
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CREATE_TOPICS: "flights:1:1,passengers_average:1:1,populated_flight:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
