version: '2'
services:
  app:
    user: root
    image: flights-analyzer:latest
    command: [app]
    volumes:
      - .:/srv/apps/flights-analyzer/app/
      - ./logs/flights-analyzer:/srv/apps/flights-analyzer/logs/
    depends_on:
      - kafka
    links:
      - kafka

  ## Confluent Stack
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CREATE_TOPICS: "flights:1:1,average_passengers:1:1,trend_origin:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
